[package]
name = "ornithology-pi"
version = "0.1.0"
edition = "2021"

[features]
default = ["nokhwa/input-v4l"]

[dependencies]
image = { version = "0.23.14", default-features = false, features = ["png", "jpeg"] }
nokhwa = { version="0.9.4" }
