[package]
name = "ornithology-pi"
version = "0.1.0"
edition = "2021"

[features]
default = ["nokhwa/input-v4l"]

[dependencies]
image = { version = "0.23.14", default-features = false, features = ["png", "jpeg"] }
imageproc = { version = "0.22", default-features = false }
lenna_core = { git = "https://github.com/lenna-project/lenna-core", branch = "main" }
lenna_yolo_plugin = { git = "https://github.com/lenna-project/yolo-plugin", branch = "main" }
lenna_birds_plugin = { git = "https://github.com/lenna-project/birds-plugin", branch = "main" }
nokhwa = { version="0.9.4" }
tract-onnx = { version = "0.15.9-pre", git = "https://github.com/chriamue/tract.git", branch = "main" }
