name: Build LaTeX document

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: manual.tex
          working_directory: manual
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: prepare folder
        run: mkdir docs && cp manual/manual.pdf docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: docs