name: Build LaTeX document

on:
  workflow_run:
    workflows: ["Build and Deploy Web"]
    types:
      - completed

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: manual.tex
          working_directory: manual
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: prepare folder
        run: mkdir -p docs && cp manual/manual.pdf docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: true
