name: Release

on:
  push:
    branches: [ main ]
    #tags:
    #  - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cross
      - run: cross build --release --target armv7-unknown-linux-gnueabihf
